/**
 * apps/client-caregiver/src/components/dashboard/AIDigestPanel.jsx  MODIFY
 *
 * AI-generated daily digest panel for the caregiver dashboard.
 * Calls POST /api/ai/summary to generate or refresh the digest.
 * Displays generatedAt timestamp, empty state, and error state.
 */
import React, { useState, useEffect, useCallback } from 'react'
import { RefreshCw, Sparkles, Clock } from 'lucide-react'
import axiosInstance from '../../api/axiosConfig.js'

// ─── Skeleton loader ──────────────────────────────────────────────────────────
const DigestSkeleton = () => (
  <div className="space-y-2.5 mt-3">
    <div className="skeleton h-3.5 w-full rounded" />
    <div className="skeleton h-3.5 w-5/6 rounded" />
    <div className="skeleton h-3.5 w-4/5 rounded" />
    <div className="skeleton h-3.5 w-full rounded" />
    <div className="skeleton h-3.5 w-3/4 rounded" />
  </div>
)

// ─── Time formatter ──────────────────────────────────────────────────────────
function formatTime(isoString) {
  if (!isoString) return ''
  try {
    return new Date(isoString).toLocaleTimeString([], {
      hour:   '2-digit',
      minute: '2-digit',
    })
  } catch {
    return ''
  }
}

// ─── AIDigestPanel ────────────────────────────────────────────────────────────
/**
 * @param {{ elderId: string|null }} props
 */
export default function AIDigestPanel({ elderId }) {
  const [summary,     setSummary]     = useState(null)      // string | null
  const [generatedAt, setGeneratedAt] = useState(null)      // ISO string | null
  const [loading,     setLoading]     = useState(false)
  const [error,       setError]       = useState(null)

  // ── Fetch summary ──────────────────────────────────────────────────────────
  const fetchSummary = useCallback(async () => {
    if (!elderId) return
    setLoading(true)
    setError(null)
    try {
      const { data } = await axiosInstance.post('/ai/summary', { elderId })
      setSummary(data.summary)
      setGeneratedAt(data.generatedAt ?? null)
    } catch (err) {
      setError(
        err.response?.data?.error ||
        'Summary unavailable — Saathi may be resting.'
      )
    } finally {
      setLoading(false)
    }
  }, [elderId])

  // Fetch on mount and when elder changes
  useEffect(() => {
    if (elderId) fetchSummary()
    else { setSummary(null); setGeneratedAt(null); setError(null) }
  }, [elderId, fetchSummary])

  // ── Derived state ──────────────────────────────────────────────────────────
  const isEmpty = summary === 'No conversations yet today.' || summary === null

  return (
    <div className="card mt-4">
      {/* Header */}
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-[8px] bg-gradient-to-br from-[#4A9EE8] to-[#2BBD8E] flex items-center justify-center flex-shrink-0">
            <Sparkles className="w-4 h-4 text-white" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-[#1A202C]">AI Daily Digest</h3>
            <p className="text-[11px] text-[#718096]">Generated by Saathi AI</p>
          </div>
        </div>

        {/* Refresh button */}
        <button
          onClick={fetchSummary}
          disabled={loading || !elderId}
          className="flex items-center gap-1.5 text-xs font-medium text-[#4A9EE8] hover:text-blue-600 disabled:opacity-50 disabled:cursor-not-allowed transition-colors px-2 py-1 rounded-[6px] hover:bg-[#EFF6FF]"
          title="Refresh AI digest"
          type="button"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
          {loading ? 'Generating…' : 'Refresh'}
        </button>
      </div>

      {/* Content areas */}

      {/* Loading skeleton */}
      {loading && <DigestSkeleton />}

      {/* Error state */}
      {!loading && error && (
        <div className="mt-3 p-3 bg-red-50 rounded-[8px] border border-red-200">
          <p className="text-xs text-red-600">{error}</p>
          <button
            onClick={fetchSummary}
            className="text-xs text-red-700 font-medium mt-1 hover:underline"
            type="button"
          >
            Try again
          </button>
        </div>
      )}

      {/* No elder selected */}
      {!loading && !error && !elderId && (
        <div className="mt-3 flex flex-col items-center text-center py-4">
          <Sparkles className="w-8 h-8 text-[#718096] mb-2 opacity-30" />
          <p className="text-xs text-[#718096]">Select an elder to generate their AI digest.</p>
        </div>
      )}

      {/* Empty — no conversations yet */}
      {!loading && !error && elderId && isEmpty && (
        <div className="mt-3 flex flex-col items-center text-center py-4">
          <span className="text-3xl mb-2">💭</span>
          <p className="text-xs text-[#718096]">No conversations yet today.</p>
          <p className="text-[11px] text-[#A0AEC0] mt-1">
            The digest will appear once the elder chats with Saathi.
          </p>
        </div>
      )}

      {/* Summary text */}
      {!loading && !error && elderId && !isEmpty && summary && (
        <>
          <div className="mt-3 pl-3 border-l-2 border-[#4A9EE8]">
            <p className="text-sm text-[#1A202C] leading-relaxed whitespace-pre-wrap">
              {summary}
            </p>
          </div>

          {/* Generated timestamp */}
          {generatedAt && (
            <div className="mt-3 pt-3 border-t border-gray-100 flex items-center gap-1.5">
              <Clock className="w-3 h-3 text-[#A0AEC0]" />
              <p className="text-[11px] text-[#718096]">
                Generated at {formatTime(generatedAt)} · Powered by Saathi AI
              </p>
            </div>
          )}
        </>
      )}
    </div>
  )
}
